version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/site"
    labels:
      - "dependencies"
      - "javascript"
      - "automated pr"
    schedule:
      interval: "daily"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "automated pr"
    schedule:
      interval: "daily"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
