default_language_version:
  node: 23.3.0

repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.38.0
    hooks:
      - id: eslint
        args: ['--ext', '.js,.jsx,.ts,.tsx']
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ['--ignore-words=codespell.txt', '--skip=yarn.lock']
        exclude: '\.svg$'
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd client && npx eslint'
        language: node
        types: [javascript]
        files: ^client/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ['--write', '.']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      #- id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^public/sitemap\.xml$
      - id: forbid-new-submodules
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular']
ci:
  # for more information, see https://pre-commit.ci
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [shellcheck, markdown-link-check, commitlint]
  submodules: false
